### ISSUE TITLE
    tc.cuda.set_device(C.gpus[0]) IndexError: list index out of range :  training with CPU? Is it Feasible?

### ISSUE THREAD

**Issue by raphael10-collab** [FFTYYY/RoR_relation_extraction#8]
(base) raphy@pc:~/RoR_relation_extraction$ python main.py --dataset=ace_2005 --auto_hyperparam
    Hyper parameters autoset. | now time: 0s
    ------------------------------------------------------ | now time: 0s
    {'auto_hyperparam': True,
     'binary': False,
     'dataset': 'ace_2005',
     'dropout': 0.0,
     'ensemble': 1,
     'ensemble_size': 5,
     'epoch_numb': 30,
     'gene_file': 'watch/gene',
     'gene_in_data': True,
     'gene_no_rel': False,
     'gnn': True,
     'log_file': 'log.txt',
     'loss': 'loss_1',
     'matrix_nlayer': 4,
     'matrix_trans': True,
     'model_save': 'model_ace.pkl',
     'model_save_2': '',
     'no_log': False,
     'no_rel_name': 'NO_RELATION',
     'no_rel_weight': 0.25,
     'no_valid': True,
     'pos_only': False,
     'pos_thresh': 0.3,
     'rel_weight_norm': False,
     'rel_weight_smooth': 0,
     'scheduler': 'cosine',
     't2g_batch_size': 8,
     't2g_lr': 5e-05,
     't2g_seed': 2333,
     'test_rels': './data/semeval_2018_task7/keys.test.2.txt',
     'test_script': './data/semeval_2018_task7/semeval2018_task7_scorer-v1.2.pl',
     'test_text': './data/ace_2005/ace_05_processed/ace-05-splits/json-pm13/bc_test.json',
     'tmp_file_name': 'tmp_17300649.txt',
     'train_rels_1': './data/semeval_2018_task7/1.1.relations.txt',
     'train_rels_2': './data/semeval_2018_task7/1.2.relations.txt',
     'train_text_1': './data/ace_2005/ace_05_processed/ace-05-splits/json-pm13/bn+nw.json',
     'train_text_2': './data/semeval_2018_task7/1.2.text.xml',
     'valid_metric': 'macro',
     'valid_rels': './data/semeval_2018_task7/keys.test.1.1.txt',
     'valid_text': './data/ace_2005/ace_05_processed/ace-05-splits/json-pm13/bc_dev.json',
     'warmup_prop': 0.02,
     'watch_type': 'test'} | now time: 0s
    ------------------------------------------------------ | now time: 0s
    Seed set. 2333 | now time: 0s
    Traceback (most recent call last):
      File "main.py", line 95, in <module>
        main()
      File "main.py", line 54, in main
        C , logger = get_config()
      File "/home/raphy/RoR_relation_extraction/config.py", line 177, in get_config
        C , logger = after_parse_t2g(before_parse_t2g(argparse.ArgumentParser()).parse_args() , need_logger = True)
      File "/home/raphy/RoR_relation_extraction/config.py", line 168, in after_parse_t2g
        tc.cuda.set_device(C.gpus[0])
    IndexError: list index out of range
    (base) raphy@pc:~/RoR_relation_extraction$ 

I do not have CUDA .....

**Comment by FFTYYY** [comment]
Sorry for late responce. It might be hard to switch to cpu directly since the original code uses multi-gpu training, need to rerwrite some of the codes
